export const LOGIN_SUCCESS = 'loginSuccess'
export const LOGIN_FAILURE = 'loginFailure'
export const LOGIN_START = 'loginStart'
export const GET_API_DATA = 'getApiData'
export const CHANGE_COLOR = 'changeColor'